var app=angular.module("myMod",['ngRoute']);
app.config(['$routeProvider',function($routeProvider)
{
$routeProvider.
when("/story1",{templateUrl:"views/story1.html",controller:"story1Controller"}).
when("/story2",{templateUrl:"views/story2.html",controller:"story2Controller"}).
when("/story3",{templateUrl:"views/story3.html",controller:"story3Controller"}).
when("/story4",{templateUrl:"views/story4.html",controller:"story4Controller"}).
when("/story5",{templateUrl:"views/story5.html",controller:"story5Controller"}).
when("/story6",{templateUrl:"views/story6.html",controller:"story6Controller"}).
when("/story7",{templateUrl:"views/story7.html",controller:"story7Controller"}).
when("/story8",{templateUrl:"views/story8.html",controller:"story8Controller"}).
when("/story9",{templateUrl:"views/story9.html",controller:"story9Controller"}).
when("/story10",{templateUrl:"views/story10.html",controller:"story10Controller"}).
when("/story11",{templateUrl:"views/story11.html",controller:"story11Controller"}).
when("/story12",{templateUrl:"views/story12.html",controller:"story12Controller"}).
when("/story13",{templateUrl:"views/story13.html",controller:"story13Controller"}).
when("/story14",{templateUrl:"views/story14.html",controller:"story14Controller"}).
when("/story15",{templateUrl:"views/story15.html",controller:"story15Controller"}).
otherwise({redirectTo:"index.html"});
}

]);
app.controller("myController",function($scope)
{
}
);
app.controller("story1Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/06/16112058/The-Boy-Who-Cried-Wolf-Story-with-Moral-1296317650.jpg"}];
}
);
app.controller("story2Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/12/21100406/The-Fox-and-the-Stork.jpg"}];
}
);
app.controller("story3Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/06/21161207/The-Golden-Touch-story.jpg"}];
}
);
app.controller("story4Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/11/25114113/The-Lion-and-the-Mouse-story.jpg"}];
}
);
app.controller("story5Controller",function($scope)
{
$scope.image=[{src:"https://www.naukrinama.com/stressbuster/wp-content/uploads/2020/10/The-Milkmaid-and-Her-Pail-story.jpg"}];
}
);
app.controller("story6Controller",function($scope)
{
$scope.image=[{src:"https://tribuneonlineng.com/wp-content/uploads/2021/02/The-Proud-Rose-story.tif-650x430.jpg"}];
}
);
app.controller("story7Controller",function($scope)
{
$scope.image=[{src:"https://ichef.bbci.co.uk/news/976/cpsprodpb/C6DC/production/_107080905_gettyimages-654239286.jpg"}];
}
);
app.controller("story8Controller",function($scope)
{
$scope.image=[{src:"https://img.dtnext.in/Articles/2018/Dec/201812030237544411_Lifes-lessons-When-adversity-knocks-the-door_SECVPF.gif"}];
}
);
app.controller("story9Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/11/25114111/The-Greedy-Lion-story.jpg"}];
}
);
app.controller("story10Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/06/21160914/The-Needle-Tree-story.jpg"}];
}
);
app.controller("story11Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/11/25114115/The-Woodcutter-and-the-Golden-Axe-story.jpg"}];
}
);
app.controller("story12Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/11/25114110/The-Elephant-and-Her-Friends-story.jpg"}];
}
);
app.controller("story13Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/11/25114108/Friends-Forever-story.jpg"}];
}
);
app.controller("story14Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/06/21162538/The-Bear-and-Two-Friends-story.jpg"}];
}
);
app.controller("story15Controller",function($scope)
{
$scope.image=[{src:"https://cdn.cdnparenting.com/articles/2019/12/21100700/The-Ant-and-the-Grasshopper.jpg"}];
}
);